/* Interview reference: real GNU/Linux examples, not a claim of shell emulation.
 * Each row: question, answer, command/example, follow-up trap. */
(function (PS) {
  'use strict';
  PS.interviewTopics = [];
  function topic(id, title, sources, rows) {
    PS.interviewTopics.push({ id: id, title: title, sources: sources,
      questions: rows.map(function (r, i) {
        return { id: id + '-' + (i + 1), topic: id, question: r[0], answer: r[1], command: r[2] || '', trap: r[3] || '' };
      }) });
  }
  var man = function (name, section) { return ['Linux manual: ' + name, 'https://man7.org/linux/man-pages/man' + section + '/' + name + '.' + section + '.html']; };
  topic('foundations', 'Linux foundations & everyday operations', [man('hier', 7), man('ln', 1), man('symlink', 7), man('bootup', 7), man('ssh', 1)], [
    ['How do absolute paths, relative paths and the filesystem hierarchy work?', 'An absolute path starts at /. A relative path starts at the working directory. /etc commonly holds configuration, /var changing data and logs, /proc kernel/process views, and /tmp temporary files.', 'pwd\nls -lah\ncd /var/log\nrealpath ../log', 'The home directory ~ is not the same as /, and /root is normally root’s home.'],
    ['Compare a hard link and a symbolic link.', 'A hard link is another directory entry for the same inode on the same filesystem. A symbolic link stores a pathname and can cross filesystems or dangle.', 'ls -li file hardlink\nreadlink symlink\nreadlink -f symlink', 'Removing one hard link does not remove the data while other links or open references remain.'],
    ['What basic vi operations should a support engineer know?', 'Esc returns to normal mode, i enters insert mode, /pattern searches, n repeats, :w writes, :q quits and :q! discards unsaved changes.', 'vi app.conf\n# In the editor: /timeout then n; :q! to leave without saving', 'Use a reviewed configuration change procedure. The game does not emulate an interactive editor.'],
    ['How do you investigate a host that rebooted or did not boot normally?', 'Check uptime, boot history, previous-boot kernel/service logs, systemd failures and the infrastructure console. Identify panic, power, storage, boot or service failures.', 'uptime\nlast -x\njournalctl --list-boots\njournalctl -b -1 -k\nsystemctl --failed', 'An inaccessible SSH service is not proof the whole host is down.'],
    ['A deployed binary will not execute. What do you check?', 'Check executable permission, parent paths, architecture, interpreter/shebang, dynamic loader, required libraries, mount noexec and security policy.', 'file /opt/app/bin/loader\nhead -1 /opt/app/bin/load.sh\nuname -m\nreadelf -d /opt/app/bin/loader', 'No such file can refer to a missing interpreter or loader. Avoid ldd on an untrusted executable.'],
    ['How do scp, sftp and rsync differ operationally?', 'scp and sftp transfer using SSH facilities; rsync can synchronize differences over SSH. Check exit status, ownership, transfer completeness and the agreed delivery manifest.', 'sftp support@host\nrsync -avn ./staging/ support@host:/data/incoming/', 'The shown rsync command is a dry run. Trailing slashes and --delete can materially change the selection.']
  ]);
  topic('scripting', 'Shell scripting interview exercises', [
    ['Bash conditionals', 'https://www.gnu.org/software/bash/manual/html_node/Conditional-Constructs.html'],
    ['Bash loops', 'https://www.gnu.org/software/bash/manual/html_node/Looping-Constructs.html'],
    ['Bash parameters', 'https://www.gnu.org/software/bash/manual/html_node/Shell-Parameters.html'],
    ['Bash builtins', 'https://www.gnu.org/software/bash/manual/html_node/Bourne-Shell-Builtins.html']
  ], [
    ['What are $0, $1, $#, "$@" and a shebang?', '$0 identifies the script/shell, $1 the first positional argument, $# the argument count and "$@" preserves each argument separately. A shebang selects the interpreter when the script is executed directly.', '#!/bin/bash\nprintf "%s\\n" "$@"', 'Invoking sh script.sh overrides an intended Bash interpreter and may break Bash-only syntax.'],
    ['Write a conditional that checks whether a log is readable.', 'Use an explicit test and handle the missing/unreadable path. [ is a command requiring separated arguments and a closing ].', 'if [ -r "$log" ]; then\n  grep -i -- error "$log"\nelse\n  printf "%s\\n" "Log unavailable" >&2\nfi', 'The file can change after the check; still handle errors from the read.'],
    ['How do you read a text list without losing spaces or backslashes?', 'Use IFS= and read -r with a quoted variable. Each line is one record under this specific input contract.', 'while IFS= read -r line; do\n  printf "%s\\n" "$line"\ndone < hosts.txt', 'For arbitrary filenames that can contain newlines, use null-delimited input instead.'],
    ['How do you loop over several files safely?', 'Iterate quoted path arguments or use find -exec for a recursive selection. Keep filenames as arguments rather than reparsing a displayed listing.', 'for file in "app.log" "router log.txt"; do\n  grep -in -- error "$file"\ndone', 'An unmatched glob can remain literal under default Bash settings. Decide how an empty selection should behave.'],
    ['Why use traps and bounded retries in a support script?', 'A trap can clean up a temporary file on exit; bounded retries stop a transient repair loop becoming an endless source of load. Preserve the actual failure status.', 'tmp=$(mktemp) || exit 1\ntrap \'rm -f -- "$tmp"\' EXIT\n# Collect only the required diagnostic into "$tmp".', 'A trap cannot catch SIGKILL. Cleanup must be limited to the temporary resource the script created.'],
    ['Compare [ ], [[ ]], string tests and numeric tests.', '[ ] follows test syntax and needs quoting for expanded values. Bash [[ ]] provides shell-aware conditionals and pattern/regex operators. -eq is a numeric equality test; = is string equality in test.', '[ "$count" -eq 0 ]\n[ "$status" = "READY" ]\n[[ "$name" == *.log ]]', 'Validate numeric input before comparing it; [[ ]] is not portable POSIX sh syntax.']
  ]);
  topic('shell', 'Shell, pipes & redirection', [
    ['Bash redirections', 'https://www.gnu.org/software/bash/manual/html_node/Redirections.html'],
    ['Bash pipelines', 'https://www.gnu.org/software/bash/manual/html_node/Pipelines.html'],
    ['Bash quoting', 'https://www.gnu.org/software/bash/manual/html_node/Quoting.html']
  ], [
    ['How do > and >> differ from moving a file?', '> creates or truncates the destination and writes stdout. >> appends. mv changes a pathname or moves the file; it does not capture command output.', 'grep -i error app.log > errors.txt\ngrep -i warn app.log >> errors.txt\nmv errors.txt archive/', 'Redirection happens before the command runs. Never use grep error app.log > app.log.'],
    ['How do you save stdout and stderr separately or together?', 'Descriptors 0, 1 and 2 are stdin, stdout and stderr. Duplicate descriptor 2 to the current descriptor 1 to combine outputs.', './job > job.out 2> job.err\n./job > combined.log 2>&1', 'Redirections are processed from left to right.'],
    ['Why are >out 2>&1 and 2>&1 >out different?', 'The first sends both streams to out. The second first points stderr at the original stdout, then redirects only stdout to out.', './job > out 2>&1\n./job 2>&1 > out', '2>&1 duplicates a destination at that point; it does not create a permanent link.'],
    ['What does a pipe carry, and what is its exit status?', 'A pipe carries stdout into the next command’s stdin. Bash normally returns the last command’s status; pipefail returns the rightmost nonzero status, or zero if all succeed.', 'set -o pipefail\n./batch 2>&1 | tee batch.log', 'A successful tee alone does not prove the batch succeeded.'],
    ['How do you save output while still seeing it?', 'tee copies stdin to stdout and files. -a appends to the file.', 'grep -i error app.log | tee -a incident.txt', 'tee does not receive the upstream stderr unless it was redirected.'],
    ['Explain single quotes, double quotes and quoting paths.', 'Single quotes preserve literal text. Double quotes allow variable and command expansion while protecting spaces and wildcards from splitting and globbing.', 'printf "%s\n" "$HOME"\nprintf "%s\n" \'$HOME\'\ncat "file with spaces.log"', 'Quote patterns passed to find and quote variables used as paths.'],
    ['What do ;, &&, || and $? mean?', '; continues regardless of status, && continues on zero, and || continues on nonzero. $? is the most recent exit status.', './check && echo healthy\n./check || echo failed\necho $?', 'Capture $? immediately; even echo changes it.'],
    ['What is the difference between a shell variable and an exported environment variable?', 'A shell variable belongs to that shell. export passes it to subsequently launched child processes. A child cannot change its parent’s environment.', 'APP_ENV=uat\nexport APP_ENV\nprintenv APP_ENV', 'Service and cron environments can differ from your login shell.'],
    ['When do you use command substitution or xargs?', '$(command) captures output as text with trailing newlines removed. xargs constructs argument lists from input; use null delimiters for arbitrary filenames.', 'find /var/log/app -type f -name "*.log" -print0 | xargs -0 -r grep -l ERROR', 'Splitting ls output or unquoted substitution breaks spaces and newline-containing filenames.']
  ]);
  topic('grep', 'Log searching & grep', [
    ['GNU grep matching', 'https://www.gnu.org/software/grep/manual/html_node/Matching-Control.html'],
    ['GNU grep output', 'https://www.gnu.org/software/grep/manual/html_node/General-Output-Control.html'],
    ['GNU grep context', 'https://www.gnu.org/software/grep/manual/html_node/Context-Line-Control.html']
  ], [
    ['Find error lines regardless of capitalization, with line numbers.', '-i ignores case and -n prefixes line numbers. A basic search is case-sensitive.', 'grep -in -- "error" app.log', 'grep -i does not mean in-place editing.'],
    ['Count error lines and count error occurrences: are they the same?', '-c counts matching lines. -o prints each nonempty match, so piping to wc -l counts occurrences.', 'grep -ic error app.log\ngrep -io error app.log | wc -l', 'A line with three errors contributes one to -c.'],
    ['Find ERROR or WARN but exclude heartbeat chatter.', 'Use extended-regex alternation and a second inverted match.', 'grep -E "ERROR|WARN" app.log | grep -vi heartbeat', 'A plain grep pattern containing | is not alternation unless extended syntax is selected.'],
    ['How do you search for a literal order ID containing regex punctuation?', 'Use -F for fixed strings and -- to end option parsing.', 'grep -Fn -- "ORD[42].A" app.log', 'A substring match can still match a longer ID. Include delimiters or parse the field.'],
    ['Which logs contain a matching message, recursively?', '-r searches directories and -l prints matching filenames.', 'grep -ril -- "sequence gap" /var/log/app', 'Scope the tree and time window; reading every log on a stressed shared mount can worsen an incident.'],
    ['How do you view context around an exception?', '-B selects preceding lines, -A following lines, and -C both. Check enough context to include the causal exception.', 'grep -n -B 3 -A 12 Exception app.log', 'Line context is not a complete multiline parser.'],
    ['How do you inspect rotated logs and follow rotation?', 'zgrep searches gzip logs. tail -f follows an open descriptor; GNU tail -F follows the filename and retries after replacement.', 'zgrep -i error app.log.2.gz\ntail -F app.log', 'An empty current log does not prove no errors occurred before rotation.'],
    ['How do you interpret grep exit codes?', 'Ordinarily 0 means a match, 1 no match and 2 an error. Check diagnostics before treating no output as proof of health.', 'grep -q -- "READY" app.log\necho $?', 'GNU grep -q may return success if a match was found even when another error occurred.'],
    ['How do you correlate one failed order across services?', 'Start with the business date, timezone and client/order/correlation ID. Trace ingress, validation, routing, venue acknowledgement and persistence; record the first missing transition.', 'grep -F "ClOrdID=ORD-1042" gateway.log router.log capture.log', 'Timestamp proximity alone is weak evidence when clocks drift or processing is asynchronous.']
  ]);
  topic('text', 'awk, sed & text processing', [
    ['GNU awk records', 'https://www.gnu.org/software/gawk/manual/html_node/Records.html'],
    ['GNU awk fields', 'https://www.gnu.org/software/gawk/manual/html_node/Fields.html'],
    ['GNU awk patterns', 'https://www.gnu.org/software/gawk/manual/html_node/Pattern-Overview.html'],
    ['GNU sed', 'https://www.gnu.org/software/sed/manual/sed.html'],
    ['GNU sort', 'https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html']
  ], [
    ['Extract fields from whitespace-delimited or simple comma-delimited data.', 'awk uses whitespace by default; -F sets the field separator. $0 is the full record, $1 the first field, and NF the field count.', 'awk \'{print $1, $3}\' app.log\nawk -F, \'{print $2}\' trades.csv', 'awk -F, is not a full CSV parser for quoted commas or multiline fields.'],
    ['Find trades above a numeric threshold and total their quantity.', 'Use a field condition and an accumulator; print the total in END. This example has a header and quantity in column 4.', 'awk -F, \'NR>1 && $4>1000 {print $1, $4}\' trades.csv\nawk -F, \'NR>1 {sum+=$4} END {print sum+0}\' trades.csv', 'Floating-point awk arithmetic is unsuitable for exact monetary reconciliation without a defined precision policy.'],
    ['Print a line range with awk or sed.', 'NR counts records across all input files; FNR restarts per file. sed -n suppresses automatic output and p explicitly prints.', 'awk \'NR>=100 && NR<=120\' app.log\nsed -n \'100,120p\' app.log', 'Without -n, sed can print both the automatic output and the explicit p output.'],
    ['Replace text with sed and preserve the original file.', 'The s command substitutes; g replaces all matches on a line. Default sed writes a transformed stream, leaving the input intact.', 'sed \'s/uat-host/prod-host/g\' app.conf > app.conf.new', 'Review a diff before replacing live configuration; sed -i edits in place.'],
    ['Remove comments and blank lines from displayed configuration.', 'Use line-addressed deletion to remove whole matching lines from the output.', 'sed \'/^[[:space:]]*#/d; /^[[:space:]]*$/d\' app.conf', 'This does not parse comments inside quoted values or remove inline comments safely.'],
    ['Count unique values and show the most frequent ones.', 'uniq combines adjacent duplicates, so sort first. Numeric reverse sorting puts the biggest counts first.', 'cut -d, -f3 trades.csv | sort | uniq -c | sort -nr | head', 'Exclude headers and understand whether the field can contain delimiters.'],
    ['How do sort -n, sort -k and sort -u differ?', '-n uses numeric comparison; -k selects keys; -u emits one representative per equal sort key.', 'sort -t, -k4,4nr trades.csv\nsort -u ids.txt', 'Locale affects ordering; a key with no end position includes the rest of the line.'],
    ['When would you use tr, cut, diff, comm or jq?', 'tr translates characters; cut extracts fixed fields; diff compares files; comm compares sorted lines; jq parses JSON structurally.', 'tr "a-z" "A-Z" < names.txt\ndiff -u app.conf.old app.conf\ncomm -3 expected.sorted actual.sorted\njq -r \'select(.level=="ERROR") | .orderId\' app.jsonl', 'Use a format-aware parser for JSON and complex CSV instead of assuming every record is one simple text line.']
  ]);
  topic('files', 'Finding files, timestamps & archives', [
    ['GNU find age ranges', 'https://www.gnu.org/software/findutils/manual/html_node/find_html/Age-Ranges.html'],
    ['GNU find time tests', 'https://www.gnu.org/software/findutils/manual/html_node/find_html/Comparing-Timestamps.html'],
    man('inode', 7), ['GNU truncate', 'https://www.gnu.org/software/coreutils/manual/html_node/truncate-invocation.html'],
    ['GNU tar', 'https://www.gnu.org/software/tar/manual/html_node/Basic-Tar-Format.html']
  ], [
    ['Find regular files modified within the last 30 days.', 'Use -mtime -30 for an age of less than thirty 24-hour periods. GNU find rounds the age down before comparing.', 'find /var/log/app -type f -mtime -30 -print', 'This is 30 days, not 30 minutes. Calendar-day boundaries require a different expression.'],
    ['What do -mtime 30 and -mtime +30 mean?', '-mtime 30 matches ages from 30 to under 31 days. +30 matches rounded ages greater than 30, starting at 31 days.', 'find /var/log/app -type f -mtime +30', '+30 does not mean precisely older than 30 days.'],
    ['Find files modified in the last 30 minutes or after a date.', '-mmin measures minutes. GNU -newermt compares modification time against a parsed timestamp.', 'find /var/log/app -type f -mmin -30\nfind /var/log/app -type f -newermt "2026-09-01 00:00:00 UTC"', 'Use explicit timezones and document inclusive/exclusive boundaries.'],
    ['What are mtime, ctime and atime?', 'mtime tracks content modification; ctime tracks inode status change; atime tracks access subject to mount policy. ctime is not creation time; birth time may be separately available.', 'stat app.log\nfind /etc/app -type f -ctime -1', 'chmod can change ctime without changing file content.'],
    ['Find large logs by case-insensitive name without crossing filesystems.', '-iname ignores case in a filename pattern. -xdev stays on the starting filesystem; -size +1G selects size above one GiB using GNU size-unit rounding.', 'find /var/log -xdev -type f -iname "*.log" -size +1G', 'Quote the pattern so the shell does not expand it first.'],
    ['How do you process matching paths safely?', 'Use find -exec with {} + to pass path arguments directly. Null-delimited pipelines are another option for arbitrary filenames.', 'find /var/log/app -type f -name "*.log" -exec grep -l ERROR {} +', 'Never test a deletion command on live logs before reviewing its selection and retention requirements.'],
    ['What is truncate, and is “transcat” a Linux command?', 'The likely intended command is truncate: it sets a file’s logical length. Shrinking discards trailing data; expanding reads back as zero bytes. cat displays content.', 'truncate -s 0 scratch.log\ncat scratch.log', 'Truncating a live log destroys evidence. Use only the approved path and retention procedure.'],
    ['How do you inspect an archive and verify a transfer?', 'List an archive before extracting it into a dedicated directory. Compare a checksum with a trusted expected value, plus file count and business control totals.', 'tar -tzf eod.tar.gz\nsha256sum eod.tar.gz\ntar -xzf eod.tar.gz -C staging/', 'A checksum verifies bytes against a reference; it does not prove the reference is authentic or the business data correct.']
  ]);
  topic('permissions', 'Permissions, identity & secure access', [man('inode', 7), man('path_resolution', 7), man('acl', 5), man('umask', 2), man('ssh', 1)], [
    ['Explain 640, 750 and directory execute permission.', 'Permissions use read=4, write=2, execute=1 for owner/group/other. 640 grants owner rw and group r. Directory x allows traversal; directory r lists names.', 'ls -ld /opt/app /opt/app/conf\nls -l /opt/app/conf/app.conf', 'A readable file can still be inaccessible when a parent directory lacks traversal permission.'],
    ['Why can a user delete a read-only file?', 'Unlinking is governed mainly by write and execute permissions on the parent directory, with sticky-bit and other policy restrictions.', 'ls -ld /tmp /data/reports', 'File write permission governs content changes, not directory entry removal.'],
    ['What does umask 027 produce?', 'For a program requesting mode 666, the result is typically 640; for a directory requesting 777 it is 750. umask removes permission bits.', 'umask 027\numask', 'It does not add execute permission or change existing files. Default ACLs can affect creation.'],
    ['What are the sticky bit, setgid and setuid?', 'Sticky directories restrict deletion of other users’ entries. Directory setgid normally inherits its group. Executable setuid/setgid changes effective identity, subject to mount and security restrictions.', 'ls -ld /tmp /shared/app', 'These are distinct from ordinary x permission; use privileged bits sparingly.'],
    ['A file shows the right mode but access is denied. What next?', 'Check effective user/groups, every parent directory, ACLs, SELinux/AppArmor denials, mount flags and the service’s namespace.', 'id\nnamei -l /opt/app/conf/app.conf\ngetfacl /opt/app/conf/app.conf\nls -Z /opt/app/conf/app.conf', 'chmod 777 or disabling policy is not a diagnosis.'],
    ['Why does sudo echo text > protected-file fail?', 'The current shell opens the redirection before sudo runs echo. A privileged writer such as tee opens the target under sudo.', 'printf "%s\\n" "setting=value" | sudo tee /etc/app/setting.conf', 'This example changes configuration and requires the normal change procedure.'],
    ['How do you investigate SSH/SFTP authentication failures?', 'Separate name resolution, TCP reachability, host-key verification and authentication. Check account, authorized keys, ownership, server logs and allowed authentication methods.', 'ssh -v support@host\nsftp support@host\nssh-keygen -lf known_host_key.pub', 'Verify a changed host key independently. Do not disable host-key checking as the permanent fix.']
  ]);
  topic('processes', 'Processes, signals & jobs', [man('ps', 1), man('signal', 7), man('wait', 2), man('proc_pid_limits', 5)], [
    ['How do you find the process, owner and parent?', 'Inspect PID, PPID, user, start time and full arguments. A PID can be reused, so verify identity before sending a signal.', 'ps -eo pid,ppid,user,lstart,args\npgrep -af trade-router', 'A string match is a candidate, not proof that it is the process you intend to stop.'],
    ['Explain R, S, D, T and Z states.', 'R is running or runnable; S interruptible sleep; D usually uninterruptible kernel wait; T stopped; Z exited but awaiting collection by a parent.', 'ps -eo pid,ppid,stat,wchan:32,comm', 'Java BLOCKED describes monitor contention and is not equivalent to Linux D.'],
    ['Why start with SIGTERM rather than SIGKILL?', 'TERM allows a handler to close sessions and flush state. KILL cannot be caught, blocked or ignored, and bypasses application cleanup.', 'kill -TERM 4820', 'A timeout policy may require KILL after evidence capture; verify recovery and business state afterward.'],
    ['Can kill -9 always immediately remove a D-state process?', 'No. A truly uninterruptible wait may delay fatal-signal handling until the wait completes. Some kernel waits are killable, so the exact wait path matters.', 'ps -o pid,stat,wchan:32 -p 4820\ncat /proc/4820/stack', 'Repeated kill commands do not repair a failed storage path.'],
    ['How do you remove a zombie?', 'The process has already exited. Its parent or designated reaper must collect its exit status with wait; investigate the parent’s reaping behavior.', 'ps -eo pid,ppid,stat,comm', 'Sending SIGKILL to the zombie cannot make it run cleanup.'],
    ['Compare nohup, &, jobs, bg and fg.', '& launches an asynchronous job. nohup arranges SIGHUP to be ignored and may redirect terminal output. jobs lists shell jobs; bg/fg resume them in background/foreground.', 'nohup ./report > report.log 2>&1 &\njobs -l', 'nohup is not a restart policy or replacement for a managed production service.'],
    ['How do you diagnose “Too many open files”?', 'Compare actual open descriptors and growth against the affected process’s soft/hard limits. Distinguish per-process EMFILE from system-wide ENFILE.', 'cat /proc/4820/limits\nls /proc/4820/fd | wc -l\nlsof -p 4820', 'ulimit in your login shell does not report or change the running service’s limits.']
  ]);
  topic('cpu', 'CPU, load & latency', [man('top', 1), man('vmstat', 8), man('mpstat', 1), man('pidstat', 1), ['Kernel PSI', 'https://www.kernel.org/doc/html/latest/accounting/psi.html']], [
    ['Is load average the same as CPU utilization?', 'No. Linux load includes runnable tasks and tasks in uninterruptible sleep. Compare with CPU capacity, queueing and blocked I/O.', 'uptime\nlscpu\nvmstat 1 5', 'Load 8 has different implications on 2 CPUs and 32 CPUs.'],
    ['What do the 1-, 5- and 15-minute load averages tell you?', 'They are smoothed load measures over different timescales. A high short average relative to longer averages suggests rising load, not the exact incident start time.', 'uptime', 'They are not simple percentages or three independent CPU samples.'],
    ['A Java process shows 350% CPU. Is that possible?', 'In the common per-core top mode, 100% corresponds to one logical CPU. A multithreaded process can use several CPUs.', 'top -H -p 4820\nmpstat -P ALL 1 5', 'top modes and other tools normalize percentages differently.'],
    ['How do you identify a hot Java thread?', 'Find the native thread ID, convert it to hexadecimal and match it to nid in a contemporaneous thread dump. Repeat samples to distinguish sustained work from a transient spike.', 'top -H -p 4820\nprintf "%x\\n" 4831\njcmd 4820 Thread.print', 'Container PID namespaces can change the IDs visible inside and outside the container.'],
    ['What do user, system, iowait and steal mean?', 'User is userspace execution; system is kernel work; iowait accounts idle CPU time associated with outstanding I/O; steal indicates virtual CPU time withheld by the hypervisor.', 'mpstat 1 5', 'iowait is not disk utilization or a direct per-process wait percentage.'],
    ['How do you interpret vmstat r, b, si and so?', 'r is runnable tasks, b blocked tasks, si swap-in and so swap-out rates. Sample repeatedly and compare trends with latency.', 'vmstat 1 5', 'The first report includes averages since boot for rate fields; later reports describe the interval.'],
    ['A server has idle CPU but the application is slow. What next?', 'Look for a single saturated thread, locks, I/O, dependency latency, CPU affinity, cgroup throttling and queue buildup. Measure where time is spent.', 'pidstat -t -p 4820 1 5\ncat /proc/pressure/cpu\ncat /proc/pressure/io', 'Low average CPU does not exclude a bottleneck.'],
    ['Would nice or CPU pinning fix a slow service?', 'nice changes scheduling priority under contention. Affinity limits eligible CPUs; either can help or harm depending on competing work and NUMA locality.', 'ps -o pid,ni,psr,comm -p 4820\ntaskset -pc 4820', 'Measure before changing priorities, real-time policy or affinity on trading hosts.']
  ]);
  topic('memory', 'Memory, swap & OOM', [man('free', 1), man('proc_meminfo', 5), man('proc_pid_smaps', 5), ['Kernel memory overcommit', 'https://www.kernel.org/doc/html/latest/admin-guide/mm/overcommit-accounting.html']], [
    ['Linux has little free RAM. Is that an incident?', 'Not by itself. Inspect available memory, reclaimable cache, swap activity and pressure rather than free memory alone.', 'free -m\ngrep -E "MemAvailable|Cached|SReclaimable" /proc/meminfo', 'Cache is useful; routinely dropping it can increase latency.'],
    ['Explain RSS, VSZ and PSS.', 'RSS is resident physical memory mapped by a process; VSZ is virtual address space; PSS apportions shared pages between their users.', 'ps -o pid,rss,vsz,comm -p 4820\ncat /proc/4820/smaps_rollup', 'Summing RSS across processes can double-count shared pages.'],
    ['Does occupied swap mean the server is thrashing?', 'No. Cold pages may remain swapped out. Thrashing is sustained page movement and reclaim with poor progress or latency.', 'free -m\nvmstat 1 5\nsar -W 1 5', 'Look at rates and pressure, not only the amount of swap used.'],
    ['Distinguish a page fault from a segmentation fault.', 'A page fault asks the kernel to resolve a memory mapping or resident-page condition; many are normal. SIGSEGV indicates an invalid access that the kernel could not permit.', 'pidstat -r -p 4820 1 5', 'Minor faults need no disk fetch; major faults may involve storage.'],
    ['How do you investigate a process that disappeared under memory pressure?', 'Check kernel and service logs, exit status, cgroup memory events and deployment limits. Distinguish an OOM kill from a manual kill or crash.', 'journalctl -k --since "30 minutes ago"\ncat /sys/fs/cgroup/app/memory.events', 'Exit 137 indicates SIGKILL under a common convention; it is not proof of OOM.'],
    ['How do you prove a memory leak?', 'Compare repeated measurements under comparable load: resident memory, retained heap after collection, allocation and ownership. Look for growing live data that no longer serves a purpose.', 'pidstat -r -p 4820 1 5\npmap -x 4820', 'Growth alone can be cache warming, mapping or a workload change.'],
    ['What are overcommit, huge pages and NUMA concerns?', 'Overcommit concerns promises of virtual memory; huge pages affect translation and allocation behavior; NUMA affects the cost of accessing memory on another node.', 'grep -E "CommitLimit|Committed_AS|Huge" /proc/meminfo\nnumastat -p 4820', 'Settings are workload-specific. Do not assume disabling swap or enabling huge pages always improves latency.']
  ]);
  topic('disk', 'Disk, inodes, I/O & NFS', [man('df', 1), man('du', 1), man('iostat', 1), man('unlink', 2), man('nfs', 5)], [
    ['Why do df and du disagree?', 'df reports filesystem allocation; du walks reachable paths. Deleted open files, snapshots, reserved blocks, hidden mount contents, sparse files or permissions can explain differences.', 'df -h\ndu -xsh /var/log\nlsof +L1', 'Use the same filesystem and scope for a meaningful comparison.'],
    ['“No space left” but df -h looks fine: what next?', 'Check inode exhaustion, quotas and which filesystem actually backs the failing path, including tmpfs or a container overlay.', 'df -i /var/log/app\nfindmnt -T /var/log/app\nquota -s', 'A read-only filesystem and permission denial are different error classes.'],
    ['A deleted log is still consuming space. What is the mechanism?', 'An open file description retains the inode and blocks after unlink. Space is freed when its last reference closes, or when the file is appropriately truncated.', 'lsof +L1\nls -l /proc/4820/fd', 'Prefer the documented log-reopen procedure. Truncating a descriptor can lose evidence and does not reset the writer’s offset.'],
    ['How do you determine whether storage latency is hurting the app?', 'Correlate request latency with device await, queue depth and throughput plus per-process I/O and blocked tasks.', 'iostat -xz 1 5\npidstat -d -p 4820 1 5', '100% util is not a universal saturation limit for modern parallel devices; first reports often summarize since boot.'],
    ['What is a sparse file?', 'Its logical size can exceed allocated blocks because unwritten holes read as zeros.', 'ls -lh sparse.dat\ndu -h sparse.dat\nstat sparse.dat', 'Copying with an unsuitable tool or option may materialize holes and consume much more space.'],
    ['Explain a hard NFS mount hang and why soft is not a universal fix.', 'A hard mount retries unavailable operations; callers can wait in the kernel. Soft timeout behavior can expose applications to I/O errors and data-integrity risks.', 'findmnt -t nfs,nfs4\nnfsstat -m\nps -eo pid,stat,wchan:32,comm', 'Restore the dependency or follow a tested failover procedure instead of blindly remounting.'],
    ['What do you check for a read-only filesystem or storage error?', 'Inspect the exact error, mount flags and kernel/device logs. A filesystem may have remounted read-only after an error.', 'findmnt -T /data\njournalctl -k --since "30 minutes ago"\nlsblk -f', 'Do not run an offline repair tool against a live mounted filesystem without the prescribed recovery plan.']
  ]);
  topic('tcp', 'TCP & socket investigation', [man('ss', 8), man('tcp', 7), ['TCP standard (RFC 9293)', 'https://www.rfc-editor.org/rfc/rfc9293.html']], [
    ['Explain every flag in ss -nptl.', '-n keeps addresses/ports numeric, -p shows process ownership where permitted, -t selects TCP and -l selects listeners. Flag order is interchangeable.', 'ss -nptl', 'A listener is not evidence of an established FIX session or healthy order processing.'],
    ['How do you inspect connected TCP sockets versus every TCP socket?', 'ss -tnp displays non-listening TCP sockets; -a includes listeners. State filters narrow the investigation.', 'ss -tnp\nss -tanp\nss -tnp state established', 'Process details may be hidden by permissions or namespaces.'],
    ['Describe the TCP handshake and what it guarantees.', 'The usual handshake is SYN, SYN-ACK, ACK. TCP provides an ordered byte stream with retransmission; it does not preserve message boundaries or acknowledge business processing.', 'tcpdump -nn -i eth0 -c 30 "tcp port 9876"', 'A successful connection test is only transport evidence.'],
    ['Compare connection refused, timeout and connection reset.', 'Refused commonly follows a reject/RST when nothing accepts the connection. Timeout means no required response arrived in time. Reset terminates an existing or attempted connection abruptly.', 'nc -vz -w 3 venue.example 9876\nss -tnp state syn-sent', 'Firewalls, load balancers and intermediate devices can produce similar symptoms.'],
    ['What do CLOSE_WAIT and TIME_WAIT suggest?', 'CLOSE_WAIT means the peer closed and the local application has not completed its close. TIME_WAIT normally protects a recently closed connection from delayed segments.', 'ss -tanp state close-wait\nss -tan state time-wait', 'Neither state alone proves a leak. Compare counts, ages and workload.'],
    ['How do you interpret Recv-Q and Send-Q?', 'For established TCP, they reflect unread received bytes and outstanding send-side data. For a listener, the queues describe accepted-connection backlog occupancy and its limit.', 'ss -ltn\nss -tinp', 'Listener queue numbers are not application payload byte counts.'],
    ['How do you investigate retransmissions or a zero window?', 'Compare interval counters and per-socket diagnostics with packet evidence. Retransmissions suggest loss or delayed acknowledgement; a zero window points to receive-side flow control.', 'ss -tinp\nnstat -az\nsar -n TCP,ETCP 1 5', 'Retransmission does not by itself identify the failing hop or prove a physical network fault.'],
    ['What are ephemeral ports, backlog and keepalives?', 'Clients commonly use ephemeral source ports. Listen backlog queues connections awaiting acceptance. TCP keepalive probes idle peers when enabled; FIX heartbeats test a different layer.', 'cat /proc/sys/net/ipv4/ip_local_port_range\nss -s', 'Port exhaustion, socket leaks and slow accept loops need different remedies; avoid blanket TCP tuning.']
  ]);
  topic('udp', 'UDP, multicast & packet capture', [man('udp', 7), man('ip', 7), man('tcpdump', 8), man('ss', 8)], [
    ['Compare UDP with TCP for market data.', 'UDP preserves datagrams but does not guarantee delivery, order or duplicate suppression. Multicast can distribute one feed to many receivers; feed protocols implement sequence detection and recovery.', 'ss -uanp', 'UDP is not automatically faster for every application or network.'],
    ['Why does ss -unp sometimes miss a market-data receiver?', 'By default ss omits listening/unconnected bound sockets. Add -a to include all UDP sockets or use -l for bound receiving sockets.', 'ss -uanp\nss -ulnp', 'UDP has no TCP-style LISTEN handshake even when a tool groups bound sockets under listening.'],
    ['How do you localize UDP packet loss?', 'Compare sender/feed sequence gaps, NIC drops, IP/UDP error counters, socket drops and application drain rates over the same interval.', 'ip -s link show eth1\nnetstat -su\nss -uamn', 'A large cumulative error counter may predate the incident.'],
    ['What does a growing UDP Recv-Q suggest?', 'Data is queued for the receiving socket and may not be drained fast enough. Investigate CPU scheduling, locks, application pauses and burst rates.', 'ss -uanp\ntop -H -p 6120', 'Increasing buffers may absorb bursts but cannot fix a permanently blocked consumer.'],
    ['How do you troubleshoot multicast membership?', 'Check destination group, port, interface, source filter, routing and switch IGMP behavior. Confirm the application joined the correct group on the intended interface.', 'ip maddr show dev eth1\nnetstat -g\ncat /proc/net/igmp', 'A group shown on a host does not prove the target process consumes the right feed or source.'],
    ['Capture a small, relevant sample without name resolution.', 'Choose the correct interface, use numeric output, restrict the host/port and bound packet count. A pcap written with -w can be inspected later.', 'tcpdump -nn -i eth1 -c 100 -s 128 -w sample.pcap "udp and dst host 239.10.20.30 and port 15000"', 'A limited snap length may omit payload. Captures can contain trading data; use approved storage and access.'],
    ['Packets arrive at the NIC but prices are stale. What next?', 'Check kernel/socket delivery, multicast join, feed sequence, decoder errors, consumer threads, internal queues and the final publishing path.', 'ss -uanp\nnetstat -su\njcmd 6120 Thread.print', 'NIC packet capture proves observation at that interface, not successful application processing.']
  ]);
  topic('network', 'IP, DNS, routes & firewalls', [man('ip-route', 8), man('ip-address', 8), man('nsswitch.conf', 5), ['ISC dig', 'https://bind9.readthedocs.io/en/latest/manpages.html#dig-dns-lookup-utility']], [
    ['What do CIDR, subnet, gateway and longest-prefix routing mean?', 'CIDR gives the number of prefix bits. A route with the most specific matching prefix usually wins within the selected routing table; policy rules can choose other tables.', 'ip addr\nip route\nip route get 10.20.30.40', 'The default gateway is not used for every destination.'],
    ['How many usable IPv4 hosts are in a /24, /31 or /32?', 'A conventional /24 has 256 addresses and usually 254 host addresses. A /31 can use both addresses on a point-to-point link; a /32 identifies one address.', 'ip addr show', 'Do not apply the subtract-two rule to every prefix or to IPv6.'],
    ['The hostname fails but the IP works. How do you test DNS?', 'Compare the system resolver path with direct DNS queries, search domains, response codes, TTLs and the expected records.', 'getent hosts venue.example\ndig venue.example A\ndig venue.example AAAA\ncat /etc/resolv.conf\ncat /etc/nsswitch.conf', 'dig can bypass /etc/hosts and parts of the application resolver behavior.'],
    ['What do NXDOMAIN, SERVFAIL and DNS timeout imply?', 'NXDOMAIN says the queried name does not exist in the response context. SERVFAIL means the resolver failed to answer successfully. Timeout means no answer arrived before the deadline.', 'dig @10.0.0.53 venue.example', 'Negative caching and split DNS can make different clients see different results.'],
    ['Ping fails but HTTPS works. Is that contradictory?', 'No. ICMP may be filtered while TCP is permitted. Test the actual protocol, destination port and application path.', 'ping -c 3 venue.example\ncurl --connect-timeout 3 --max-time 10 https://venue.example/health', 'Ping success also does not prove TCP or application health.'],
    ['How do ARP/neighbor tables, MTU and duplex affect troubleshooting?', 'Neighbors map local-link destinations; MTU limits packet size; link settings and errors can reveal interface problems.', 'ip neigh\nip -s link\nethtool eth0\ntracepath venue.example', 'Large-packet failure may involve path MTU discovery even when small pings work.'],
    ['A local connection works but a remote connection fails. What do you inspect?', 'Check bind address, IPv4/IPv6, route and return route, host/network firewalls, security policy, NAT and load-balancer health.', 'ss -nptl\nip route get 10.20.30.40\nsudo nft list ruleset', 'Binding to 127.0.0.1 limits access to that network namespace’s loopback.'],
    ['How do you distinguish a network problem from a slow dependency?', 'Measure name lookup, connect, TLS and response timing separately, and correlate both ends with request IDs and socket queues.', 'curl -sS -o /dev/null -w "dns=%{time_namelookup} connect=%{time_connect} tls=%{time_appconnect} first=%{time_starttransfer} total=%{time_total}\\n" --max-time 10 https://venue.example/health', 'curl timing values are cumulative milestones, not independent phase durations.']
  ]);
  topic('tls', 'HTTP, TLS & certificates', [
    ['curl manual', 'https://curl.se/docs/manpage.html'],
    ['OpenSSL s_client', 'https://docs.openssl.org/master/man1/openssl-s_client/'],
    ['OpenSSL x509', 'https://docs.openssl.org/master/man1/openssl-x509/']
  ], [
    ['TCP connects but HTTPS fails. What could be wrong?', 'Check SNI, hostname, certificate chain, validity dates, trusted CA, protocol/cipher compatibility, mutual TLS requirements and proxy configuration.', 'openssl s_client -connect venue.example:443 -servername venue.example -verify_hostname venue.example -verify_return_error', 'Basic s_client output can continue after verification errors unless verification failure is made fatal.'],
    ['How do you inspect certificate expiration and identity?', 'Read validity, subject, issuer and subject alternative names; verify the deployed chain and the client’s trust configuration.', 'openssl x509 -in server.pem -noout -dates -subject -issuer -ext subjectAltName', 'A certificate on disk may differ from the one served by a proxy or load balancer.'],
    ['Is curl -k a proper certificate-expiry fix?', 'No. It disables verification. Repair renewal, chain deployment, hostname or trust configuration and test with verification enabled.', 'curl -v --connect-timeout 3 --max-time 10 https://venue.example/health', 'Avoid recording credentials or sensitive response bodies in shared diagnostic logs.'],
    ['How do you distinguish HTTP 401, 403, 429, 502, 503 and 504?', '401 concerns authentication, 403 denied access, 429 rate limiting; 502 indicates an invalid upstream response, 503 unavailable service and 504 a gateway timeout.', 'curl -sS -D - -o /dev/null --max-time 10 https://venue.example/health', 'The status code is evidence from the responding layer, not a complete root cause.'],
    ['Why can curl exit zero for HTTP 500?', 'Without a fail option, a completed HTTP exchange can count as transfer success. Inspect the status or use --fail-with-body where available.', 'curl --fail-with-body --max-time 10 https://venue.example/health', 'Separate transport errors, HTTP errors and a business error inside an HTTP 200 body.']
  ]);
  topic('services', 'systemd, logs & deployments', [man('systemctl', 1), man('journalctl', 1), man('systemd.service', 5)], [
    ['How do you investigate a service that will not start?', 'Read status, recent unit logs and effective unit configuration; check executable paths, permissions, dependencies, environment and exit reasons.', 'systemctl status trade-router --no-pager\njournalctl -u trade-router --since "30 minutes ago" --no-pager\nsystemctl cat trade-router', 'Repeated restart attempts may hide useful evidence or hit restart limits.'],
    ['Differentiate start, enable, reload, restart and daemon-reload.', 'start launches now; enable configures activation links; reload asks a running service to reload its configuration; restart stops/starts; daemon-reload rereads systemd unit definitions.', 'systemctl is-active trade-router\nsystemctl is-enabled trade-router', 'enable alone does not necessarily start now, and daemon-reload does not reload the application’s config.'],
    ['How do you inspect logs for this boot, the previous boot and the kernel?', 'journalctl can filter by boot, unit, time and priority. Previous boots require retained journal data.', 'journalctl -b -u trade-router\njournalctl -b -1 -u trade-router\njournalctl -k -p warning', 'Applications may also write separate files; absence from the journal is not proof of no event.'],
    ['systemctl says active. Does that prove the application is healthy?', 'No. Validate the expected process, listener, dependency access, application response and an approved business-path check.', 'systemctl is-active trade-router\nss -nptl\ncurl --max-time 5 http://127.0.0.1:8080/health', 'A green health endpoint may test only liveness, not downstream trading readiness.'],
    ['What do you capture before restarting a failing application?', 'Capture scope, timestamps, logs, process identity, sockets, resource usage and selected dumps if their overhead is acceptable. Confirm restart scope, state recovery and rollback.', 'ps -ef\nss -tanp\nfree -m\ndf -h', 'Restoration comes with verification of in-flight orders and persisted data, not just a new PID.'],
    ['What makes a deployment rollback safe?', 'Know the last good version, config and dependency compatibility, schema changes, traffic drain, state ownership and validation criteria. Preserve evidence of the change.', 'readlink -f /opt/app/current\ndiff -u app.conf.previous app.conf', 'Rolling back binaries alone may be incompatible with a migrated database or changed session state.']
  ]);
  topic('batch', 'Batch, scripting & file delivery', [man('crontab', 5), man('flock', 1), ['Bash manual', 'https://www.gnu.org/software/bash/manual/bash.html']], [
    ['Explain 0 6 * * 1-5 and the day-field trap in cron.', 'It schedules at 06:00 Monday through Friday in the scheduler’s timezone. In common cron implementations, restricted day-of-month and day-of-week fields are combined with OR.', 'crontab -l', 'DST handling and timezone support vary; verify the deployed scheduler.'],
    ['A script works interactively but fails from cron. Why?', 'Compare user, working directory, shell, PATH, environment, permissions, locale and credentials. Use explicit paths and capture both output streams.', 'cd /opt/app && /opt/app/bin/load > /var/log/app/load.log 2>&1', 'Do not assume login profiles are sourced by cron.'],
    ['How do you prevent overlapping batch runs?', 'Use the scheduler’s concurrency controls or a suitable lock whose lifetime covers the job, and define what a skipped run means.', 'flock -n /var/lock/eod-load.lock /opt/app/bin/eod-load', 'A local lock may not coordinate multiple hosts or provide reliable distributed ownership.'],
    ['What makes a batch restart idempotent?', 'Re-running the same business operation produces the intended single result. Use business keys, checkpoints, transactions and duplicate detection; identify partial commits before replay.', 'autorep -J EOD_POSITION_LOAD -q', 'Exit code zero and scheduler SUCCESS do not establish record completeness.'],
    ['A predecessor is late. Should you force its dependent job to SUCCESS?', 'First identify the dependency and business cutoff, validate delivered inputs, then use the approved recovery path. A scheduler status change does not create missing business data.', 'autorep -J EOD_POSITION_LOAD', 'Skipping controls can propagate incomplete positions into risk, P&L and downstream reports.'],
    ['How do you know an inbound file is complete?', 'Use the agreed delivery contract: temporary name then final rename, marker or manifest, checksum, count, business date and schema validation.', 'stat positions.csv\nsha256sum positions.csv\nwc -l positions.csv', 'Stable size alone is only a heuristic; row count alone cannot prove data correctness.'],
    ['Which Bash practices matter in production support scripts?', 'Quote inputs, validate arguments, handle exit statuses, use bounded retries/timeouts, avoid secret logging and clean up temporary files with traps.', 'bash -n job.sh\ntimeout 30s /opt/app/bin/check', 'set -e has context-dependent exceptions; it is not a substitute for intentional error handling.']
  ]);
  topic('time', 'Time, timezones & market cutoffs', [
    ['chronyc manual', 'https://chrony-project.org/doc/4.6/chronyc.html'],
    man('clock_gettime', 2), man('timedatectl', 1)
  ], [
    ['Why is time synchronization important on a trading platform?', 'Clock offsets distort cross-host event ordering, latency calculations, certificate checks and session timestamp validation. Confirm both synchronization health and business timezone.', 'date -u\ntimedatectl\nchronyc tracking\nchronyc sources -v', 'A running time service does not prove synchronization or acceptable offset.'],
    ['Explain NTP versus PTP and what you would check.', 'Both synchronize clocks; PTP can use hardware timestamping and specialized network support for tighter accuracy. Check source, measured offset, stability and the deployment’s required tolerance.', 'chronyc tracking\nchronyc sources -v', 'There is no universal tolerance for every desk; use the firm’s defined requirement.'],
    ['Why use a monotonic clock for elapsed duration?', 'Wall clock can be adjusted. A monotonic clock avoids backwards wall-clock jumps for elapsed-time measurement, though exact clock behavior depends on the clock ID.', 'date -u', 'UTC timestamps remain useful for correlation; they are not interchangeable with monotonic intervals.'],
    ['How do you troubleshoot a batch on the wrong business date?', 'Check scheduler timezone, host/application timezone, holiday calendar, daylight-saving transition and the supplied business-date parameter.', 'date\ndate -u\ncrontab -l', 'Trading date, calendar date and settlement date are not necessarily the same.'],
    ['Can clock differences make a measured latency negative?', 'Yes, when timestamps come from unsynchronized hosts or incompatible timezone/precision formats. Compare the measuring points and clock offsets before blaming packet order.', 'chronyc tracking\ngrep -F "ORD-1042" gateway.log venue.log', 'Do not silently change timestamps to make a report look consistent; preserve raw evidence.']
  ]);
  topic('java', 'JVM & application diagnostics', [
    ['Oracle jcmd', 'https://docs.oracle.com/en/java/javase/21/docs/specs/man/jcmd.html'],
    ['Oracle troubleshooting OOME', 'https://docs.oracle.com/en/java/javase/21/troubleshoot/troubleshoot-memory-leaks.html'],
    ['Java thread states', 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.State.html']
  ], [
    ['Does -Xmx limit the entire JVM process?', 'No. It limits Java heap. Metaspace, thread stacks, code cache, direct buffers and native libraries also consume memory.', 'jcmd 4820 VM.flags\nps -o rss,vsz -p 4820', 'Allow native-memory headroom beneath the host or container limit.'],
    ['Distinguish Java OutOfMemoryError from a kernel OOM kill.', 'OOME is raised by the JVM for a particular allocation/resource failure. The kernel may kill a process under host or cgroup pressure without a Java exception.', 'journalctl -k --since "30 minutes ago"\ngrep -i OutOfMemoryError app.log', 'Read the OOME detail: heap, metaspace, direct buffer or native-thread failures need different investigations.'],
    ['How can GC evidence distinguish pressure from a leak?', 'Compare allocation, pause time and retained live data after collection under comparable load. Repeatedly rising post-GC occupancy suggests retention worth investigating.', 'jstat -gcutil 4820 1000 5', 'One full GC reclaim percentage cannot establish the root cause.'],
    ['What do repeated thread dumps reveal?', 'They show whether threads progress, remain waiting on the same lock, spin, or block on dependencies. Compare owners and waiters across dumps.', 'jcmd 4820 Thread.print', 'A thread dump is a snapshot, not a CPU profile; WAITING often is normal.'],
    ['What precautions apply to heap dumps and profiling?', 'Estimate impact, disk headroom, access and retention before collecting. Heap dumps can pause the JVM, be large and contain sensitive business data.', 'jcmd 4820 help GC.heap_dump', 'Exact command availability and impact depend on JDK, collector and options.'],
    ['The application hangs with low CPU. What are plausible causes?', 'Lock contention, a depleted connection pool, blocked I/O, a slow dependency or a queue consumer waiting incorrectly. Correlate thread state with queues and dependency timing.', 'jcmd 4820 Thread.print\nss -tanp\niostat -xz 1 3', 'A JVM RUNNABLE thread can still be waiting in native I/O; inspect its stack and operating-system evidence.']
  ]);
  topic('fix', 'FIX sessions, messages & recovery', [
    ['FIX session standard', 'https://www.fixtrading.org/standards/fix-session-layer-online/'],
    ['FIX session test cases', 'https://www.fixtrading.org/standards/fix-session-testcases-online/'],
    ['FIX specifications', 'https://www.fixtrading.org/standards/']
  ], [
    ['Which FIX tags do support engineers commonly inspect first?', '35 is message type, 34 sequence, 49 sender, 56 target, 52 sending time and 58 text. Use the negotiated version and counterparty dictionary.', 'grep -E "(^|[|])35=(A|5)[|]" fix.log', 'Real tag-value FIX uses SOH delimiters; pipe-delimited logs are a readable representation.'],
    ['Explain Logon, Heartbeat, TestRequest, Logout and ResendRequest.', 'Their MsgType values are A, 0, 1, 5 and 2. A TestRequest expects a Heartbeat carrying the matching TestReqID(112).', 'grep -E "(^|[|])35=(A|0|1|5|2)[|]" fix.log', 'A healthy heartbeat exchange does not establish successful order routing.'],
    ['What is the normal response to a sequence number higher than expected?', 'Identify the gap and request recovery according to the session specification and engine policy. Inspect both sides’ inbound/outbound sequence state and stores.', 'grep -E "(^|[|])35=2[|]" fix.log', 'ResendRequest uses BeginSeqNo(7) and EndSeqNo(16); zero end commonly means all subsequent messages.'],
    ['What does “MsgSeqNum too low” mean?', 'The incoming number is below the receiver’s expectation. Check duplicate flags, session identity, store recovery and reset agreements; ordinary unexpected low numbers can cause logout.', 'grep -i "MsgSeqNum too low" gateway.log', 'Do not assume every low number is invalid: duplicate and SequenceReset rules have exceptions.'],
    ['How do gap fill, sequence reset and ResetSeqNumFlag differ?', 'Gap fill uses SequenceReset(35=4), GapFillFlag(123)=Y and NewSeqNo(36). Reset mode and Logon ResetSeqNumFlag(141) have different semantics and need the agreed session procedure.', 'grep -E "(^|[|])(35=4|141=Y)[|]" fix.log', 'Resetting session state is not equivalent to replaying or reconciling lost business messages.'],
    ['What do PossDupFlag and OrigSendingTime mean?', '43=Y marks a possible duplicate retransmission. 122 carries the original sending time; the receiver must avoid reprocessing a message already handled.', 'grep -E "(^|[|])43=Y[|]" fix.log', 'PossDup is not proof that a trade is a duplicate, and it is distinct from application-level resend.'],
    ['Which fields link an order, cancellation and execution?', 'ClOrdID(11), OrigClOrdID(41), OrderID(37) and ExecID(17) are key identifiers. Inspect ExecType(150), OrdStatus(39), CumQty(14) and LeavesQty(151) against the venue dictionary.', 'grep -F "11=ORD-1042|" fix.log', 'A CancelRequest(35=F) is a request; wait for acknowledgement or rejection and account for fills in flight.'],
    ['The order send timed out. Should you resend immediately?', 'Establish whether it reached the venue or was accepted using session logs, order state and the approved inquiry/recovery mechanism. Coordinate with the trading desk before replay.', 'grep -F "ORD-1042" gateway.log fix.log', 'Transport timeout is an unknown outcome, not proof that the order failed.'],
    ['How do you troubleshoot a FIX logon failure?', 'Separate TCP/TLS from FIX identity, authentication, session schedule, version, clock skew, heartbeat settings and sequence state. Read Logout Text and compare both ends.', 'ss -tanp\ngrep -E "(^|[|])35=(A|5)[|]" fix.log', 'Bouncing a shared gateway can disconnect unaffected clients.'],
    ['What constitutes successful FIX recovery?', 'Stable session and expected sequence progression plus reconciliation of outstanding orders, fills, rejects and downstream capture, within the desk’s recovery procedure.', 'grep -F "ORD-1042" fix.log capture.log', 'CONNECTED or successful Logon alone does not prove the business state is correct.']
  ]);
  topic('containers', 'Containers, limits & advanced diagnosis', [
    ['Kernel cgroup v2', 'https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html'],
    man('namespaces', 7), man('strace', 1), ['Kernel perf', 'https://perf.wiki.kernel.org/index.php/Tutorial']
  ], [
    ['The host has free RAM but the container was OOM-killed. Why?', 'A cgroup limit can be hit independently of host free memory. Inspect current usage, configured limit and memory events in the process’s actual cgroup.', 'cat /proc/4820/cgroup\ncat /sys/fs/cgroup/app/memory.max\ncat /sys/fs/cgroup/app/memory.events', 'The sample cgroup path is illustrative; discover the deployed path and cgroup version.'],
    ['The host CPU is idle but a container is throttled. How?', 'A cgroup CPU quota can cap runtime even with host capacity available. Compare cpu.max and cpu.stat throttling changes with latency.', 'cat /sys/fs/cgroup/app/cpu.max\ncat /sys/fs/cgroup/app/cpu.stat', 'CPU requests/weights and hard quota are different controls.'],
    ['Why do ps, localhost and filesystem paths differ inside a container?', 'PID, network and mount namespaces provide different views of those resources. Inspect from the correct namespace and map host/container identity.', 'cat /proc/4820/status\nls -l /proc/4820/ns', 'A host listener and a container loopback listener are not necessarily the same endpoint.'],
    ['How does strace help when a program is stuck?', 'It shows system calls and their results, revealing repeated failures, blocked I/O or waits. Start with a bounded, scoped capture.', 'timeout 10s strace -tt -T -p 4820 -e trace=network,file -o trace.log', 'Attaching has overhead and permission requirements; traces may contain sensitive data.'],
    ['When would you use perf or eBPF-based tools?', 'Use profiling to identify hot code or kernel paths after basic evidence narrows the problem. Choose sampling scope and approved tooling appropriate to latency-sensitive processes.', 'perf stat -p 4820 -- sleep 10', 'Availability, privileges and overhead vary; do not install or enable probes ad hoc on a trading host.'],
    ['How do you distinguish a lock, deadlock, busy loop and slow dependency?', 'A lock may release normally; a deadlock forms a cycle with no progress; a loop burns CPU; a slow dependency leaves callers waiting. Repeated stacks plus CPU, I/O and queue evidence separate them.', 'top -H -p 4820\njcmd 4820 Thread.print\nss -tinp', 'One snapshot rarely proves the full causal chain.']
  ]);
  topic('support', 'Trading support scenarios & interview answers', [
    ['FIX recovery reference', 'https://www.fixtrading.org/standards/fix-session-layer-online/'],
    ['Linux diagnostic manuals', 'https://man7.org/linux/man-pages/']
  ], [
    ['What is your first five-minute response to a P1?', 'Establish business impact, affected desks/venues, onset and change history. Confirm scope with cheap checks; preserve evidence, engage owners, assign communication and investigate the most likely failing layer.', 'date -u\nuptime\nfree -m\ndf -h\nss -nptl', 'Explain the question each command answers, not just a memorized list.'],
    ['Prices are frozen but the process is running. Walk through your investigation.', 'Check feed freshness by symbol/venue, market status, packet arrival, sequence gaps, receiver queues, decode errors, consumer locks and publication. Compare an unaffected path.', 'ss -uanp\nnetstat -su\ngrep -iE "gap|stale|decode" marketdata.log', 'Keep traders informed of stale-data scope; a live process is not fresh market data.'],
    ['Order acknowledgements slow down at the open. What do you compare?', 'Measure per-stage latency and p95/p99 against baseline, request rate, one-thread CPU, GC pauses, connection pools, queue depths, network retransmits and venue response.', 'top -H -p 4820\nss -tinp\niostat -xz 1 5', 'An average can hide severe tail latency and a small group of affected orders.'],
    ['A trade is in the FIX log but missing downstream. What now?', 'Trace identifiers and business date through the gateway, execution handler, queue, capture service and database commit. Check rejects, retries, dead-letter queues and reconciliation totals.', 'grep -F "ExecID=EX-8842" gateway.log capture.log', 'A log that says sent is not proof of durable consumer or database commit.'],
    ['What should you know about database and message-queue dependencies?', 'Check connection acquisition, timeouts, pool exhaustion, query/transaction waits, replication lag, queue age and consumer lag. Escalate with timestamps and correlation IDs.', 'ss -tanp\ngrep -iE "pool|timeout|deadlock|lag" app.log', 'A reachable database port does not prove queries execute or commits succeed. Product-specific tools vary.'],
    ['How do you handle a late EOD positions file?', 'Confirm deadline and downstream impact, producer status, business date, transport, completeness controls and rerun safety. Communicate options and validate positions after recovery.', 'stat positions.csv\nwc -l positions.csv\nautorep -J EOD_POSITION_LOAD', 'Never manufacture success merely to turn the scheduler green.'],
    ['What are RTO, RPO and split-brain risks in failover?', 'RTO is the target restoration time; RPO is the target recoverable data point. Failover must establish a single valid writer and reconcile replication/session lag.', 'date -u\nsystemctl status trade-router', 'A second active writer can duplicate orders or corrupt state even when both hosts look healthy.'],
    ['What do you put in a support update and handover?', 'State impact, time, confirmed facts, current mitigation, owner, next action and next update. Handover includes outstanding risks, commands/changes, evidence locations and validation still needed.', '', 'Distinguish observation, hypothesis and proven cause. Do not present a guess as certainty.'],
    ['When is an incident resolved, and what belongs in the RCA?', 'Confirm service and business recovery with sustained observation, reconciliation and stakeholder checks. RCA records trigger, mechanism, impact timeline, detection gaps and owned preventative actions.', '', 'A restart is a mitigation; the underlying cause can remain unresolved.'],
    ['How should you answer an unfamiliar Linux interview question?', 'Clarify the distribution, scope and symptom, give a testable hypothesis, choose a low-cost diagnostic, explain possible outputs and state how you would validate the fix.', 'man ss\nman find\ncommand --help', 'No finite question bank guarantees every interview question. Practise explaining evidence and tradeoffs aloud.']
  ]);
})(PS);
